server:
  port: 8085

spring:
  application:
    name: order-service-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db?serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: toor
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
    # generateDdl: true

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/