server:
  port: 8005

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/shared_db?serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: toor
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: /swagger-ui.html
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/