server:
  port: 8082

spring:
  application:
    name: order-service-producer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: /swagger-ui.html
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/